"""Add foreign key user_id to appointments

Revision ID: 79b8e2a7bdd0
Revises: 1f3a831c198e
Create Date: 2024-10-01 16:32:00.510914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b8e2a7bdd0'
down_revision = '1f3a831c198e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dermatologist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_appointments_dermatologist_id', 'dermatologists', ['dermatologist_id'], ['id']
        )  # Name the constraint 'fk_appointments_dermatologist_id'
        batch_op.create_foreign_key(
            'fk_appointments_user_id', 'users', ['user_id'], ['id']
        )  # Name the constraint 'fk_appointments_user_id'

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_dermatologist_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointments_user_id', type_='foreignkey')
        batch_op.drop_column('dermatologist_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
